export default Object.freeze({
  requestAgent: 'requestAgent',
  agentUnavailable: 'agentUnavailable',
  requestCall: 'requestCall',
  restoreCall: 'restoreCall',
  updateGuestSocket: 'updateGuestSocket',
  error: 'error',
  check: 'check',
  ping: 'ping',
  stop: 'stop',
  candidate: 'candidate',
  offer: 'offer',
  answer: 'answer',
  credentials: 'credentials',
});
